In [1]:
import numpy as np
import pandas as pd
import datetime


# Options
pd.options.display.max_rows = 200
pd.options.display.max_columns = 200
%matplotlib inline

# Convenience for working with external src code files
%load_ext autoreload
%autoreload 2

In [2]:
df_p5 = pd.read_excel('../data/raw/Polity-Project/p5v2018.xls')
df_p5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17574 entries, 0 to 17573
Data columns (total 37 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   p5        17574 non-null  int64
 1   cyear     17574 non-null  int64
 2   ccode     17574 non-null  int64
 3   scode     17574 non-null  object
 4   country   17574 non-null  object
 5   year      17574 non-null  int64
 6   flag      17574 non-null  int64
 7   fragment  3446 non-null   float64
 8   democ     17574 non-null  int64
 9   autoc     17574 non-null  int64
 10  polity    17574 non-null  int64
 11  polity2   17311 non-null  float64
 12  durable   16315 non-null  object
 13  xrreg     17574 non-null  int64
 14  xrcomp    17574 non-null  int64
 15  xropen    17574 non-null  int64
 16  xconst    17574 non-null  int64
 17  parreg    17574 non-null  int64
 18  parcomp   17574 non-null  int64
 19  exrec     17391 non-null  float64
 20  exconst   17574 non-null  int64
 21  polcomp   17448 non-null  float64
 22  prior     1608 non-null   object
 23  emonth    1677 non-null   object
 24  eday      1677 non-null   object
 25  eyear     1677 non-null   object
 26  eprec     1680 non-null   object
 27  interim   1511 non-null   object
 28  bmonth    1517 non-null   object
 29  bday      1517 non-null   object
 30  byear     1517 non-null   object
 31  bprec     1516 non-null   object
 32  post      1501 non-null   object
 33  change    2442 non-null   object
 34  d5        1525 non-null   object
 35  sf        529 non-null    object
 36  regtrans  2449 non-null   object
dtypes: float64(4), int64(15), object(18)
memory usage: 5.0+ MB

In [3]:
df_p5.describe()

,p5,cyear,ccode,year,flag,fragment,democ,autoc,polity,polity2,xrreg,xrcomp,xropen,xconst,parreg,parcomp,exrec,exconst,polcomp
count,17574.000000,1.757400e+04,17574.000000,17574.000000,17574.000000,3446.000000,17574.000000,17574.000000,17574.000000,17311.000000,17574.000000,17574.000000,17574.000000,17574.000000,17574.000000,17574.000000,17391.000000,17574.000000,17448.000000
mean,0.310516,4.041651e+06,403.970980,1940.910948,0.003187,0.228961,-0.235461,0.262775,-4.075395,-0.546416,-1.249346,-2.078867,-0.835496,0.046262,-0.264083,-1.057016,0.820654,0.046375,1.252923
std,0.462718,2.495259e+06,249.524641,60.255295,0.062124,0.711169,17.543082,17.580221,17.709822,7.111989,16.924762,16.761947,17.070721,17.352248,17.157319,17.014906,17.654657,17.352277,17.822010
min,0.000000,2.177600e+04,2.000000,1776.000000,0.000000,0.000000,-88.000000,-88.000000,-88.000000,-88.000000,-88.000000,-88.000000,-88.000000,-88.000000,-88.000000,-88.000000,-88.000000,-88.000000,-88.000000
25%,0.000000,2.001907e+06,200.000000,1894.000000,0.000000,0.000000,0.000000,0.000000,-7.000000,-7.000000,2.000000,1.000000,1.000000,1.000000,3.000000,1.000000,2.000000,1.000000,1.000000
50%,0.000000,3.661924e+06,366.000000,1960.000000,0.000000,0.000000,1.000000,4.000000,-3.000000,-3.000000,3.000000,1.000000,4.000000,3.000000,4.000000,3.000000,4.000000,3.000000,6.000000
75%,1.000000,6.301986e+06,630.000000,1992.000000,0.000000,0.000000,7.000000,7.000000,6.000000,7.000000,3.000000,3.000000,4.000000,7.000000,4.000000,4.000000,8.000000,7.000000,7.000000
max,1.000000,9.502018e+06,950.000000,2020.000000,2.000000,3.000000,10.000000,10.000000,10.000000,10.000000,3.000000,3.000000,4.000000,7.000000,5.000000,5.000000,8.000000,7.000000,10.000000

In [4]:
df_p5.loc[df_p5.year >= 1990]

,p5,cyear,ccode,scode,country,year,flag,fragment,democ,autoc,polity,polity2,durable,xrreg,xrcomp,xropen,xconst,parreg,parcomp,exrec,exconst,polcomp,prior,emonth,eday,eyear,eprec,interim,bmonth,bday,byear,bprec,post,change,d5,sf,regtrans
190,0,7001990,700,AFG,Afghanistan,1990,0,NaN,0,8,-8,-8.0,1,2,1,4,2,4,1,3.0,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,0,7001991,700,AFG,Afghanistan,1991,0,NaN,0,8,-8,-8.0,2,2,1,4,2,4,1,3.0,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,0,7001992,700,AFG,Afghanistan,1992,0,NaN,-77,-77,-77,0.0,0,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0,-8,4,16,1992,2,-77,NaN,NaN,NaN,NaN,NaN,-77,NaN,1,-77
193,0,7001993,700,AFG,Afghanistan,1993,0,NaN,-77,-77,-77,0.0,0,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0,NaN,NaN,NaN,NaN,NaN,-77,NaN,NaN,NaN,NaN,NaN,-77,NaN,1,-77
194,0,7001994,700,AFG,Afghanistan,1994,0,NaN,-77,-77,-77,0.0,0,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0,NaN,NaN,NaN,NaN,NaN,-77,NaN,NaN,NaN,NaN,NaN,-77,NaN,1,-77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17569,1,5522014,552,ZIM,Zimbabwe,2014,0,0.0,5,1,4,4.0,1,2,2,4,5,3,3,7.0,5,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17570,1,5522015,552,ZIM,Zimbabwe,2015,0,0.0,5,1,4,4.0,2,2,2,4,5,3,3,7.0,5,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17571,1,5522016,552,ZIM,Zimbabwe,2016,0,0.0,5,1,4,4.0,3,2,2,4,5,3,3,7.0,5,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17572,1,5522017,552,ZIM,Zimbabwe,2017,0,0.0,5,1,4,4.0,4,2,2,4,5,3,3,7.0,5,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17573,1,5522018,552,ZIM,Zimbabwe,2018,0,0.0,5,1,4,4.0,5,2,2,4,5,3,3,7.0,5,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_p5[['country', 'ccode', 'scode', 'byear', 'eyear']].dropna().drop_duplicates()

           country  ccode scode byear eyear
135    Afghanistan    700   AFG  1935  1935
145    Afghanistan    700   AFG  1945  1945
164    Afghanistan    700   AFG  1964  1964
189    Afghanistan    700   AFG  1989  1978
196    Afghanistan    700   AFG  1996  1992
...            ...    ...   ...   ...   ...
17542     Zimbabwe    552   ZIM  1987  1987
17554     Zimbabwe    552   ZIM  1999  1999
17556     Zimbabwe    552   ZIM  2001  2001
17564     Zimbabwe    552   ZIM  2009  2009
17568     Zimbabwe    552   ZIM  2013  2013

[1090 rows x 5 columns]

## Version "D"

#### Feature definitions
General

- p5: flag indicating row changed since previous version of dataset. *ignore*

Define country

- present: most recent observation for given country
- cyear: code for "country year"
- ccode: country code, numeric
- scode: country code, abbreviation
- country: country name


Dates

- polity: *recommended ignore by data manual*
- persist: rounded number of years the polity has persisted without a change in gov't classification
- bmonth: polity begin month
- bday: polity begin day
- byear: polity begin year
- emonth: polity end month
- eday: polity end day
- eyear: polity end year


Government classifiers

- democ: democracy index (0-10)
- autoc: autocracy index (0-10)
- xrreg: regulation of chief executive recruitment
- xrcomp: competitiveness of executive recruitment
- xropen: openness of executive recruitment
- xconst: executive constraints ("decision rules")
- parreg: regulation of participation
- parcomp: competitiveness of participations
- exrec: executive recruitment (combines xrreg, xrcomp, xropen)
- exconst: executive constraints (identical to xconst)
- polcomp: political competition (combines parreg and parcomp)



????? DEMOC = XRCOMP + XROPEN + XCONST + PARCOMP ?????

????? AUTOC = XRCOMP + XROPEN + XCONST + PARCOMP + PARREG ?????

In [6]:
df_p5.loc[df_p5.year >= 1990]

,p5,cyear,ccode,scode,country,year,flag,fragment,democ,autoc,polity,polity2,durable,xrreg,xrcomp,xropen,xconst,parreg,parcomp,exrec,exconst,polcomp,prior,emonth,eday,eyear,eprec,interim,bmonth,bday,byear,bprec,post,change,d5,sf,regtrans
190,0,7001990,700,AFG,Afghanistan,1990,0,NaN,0,8,-8,-8.0,1,2,1,4,2,4,1,3.0,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,0,7001991,700,AFG,Afghanistan,1991,0,NaN,0,8,-8,-8.0,2,2,1,4,2,4,1,3.0,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,0,7001992,700,AFG,Afghanistan,1992,0,NaN,-77,-77,-77,0.0,0,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0,-8,4,16,1992,2,-77,NaN,NaN,NaN,NaN,NaN,-77,NaN,1,-77
193,0,7001993,700,AFG,Afghanistan,1993,0,NaN,-77,-77,-77,0.0,0,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0,NaN,NaN,NaN,NaN,NaN,-77,NaN,NaN,NaN,NaN,NaN,-77,NaN,1,-77
194,0,7001994,700,AFG,Afghanistan,1994,0,NaN,-77,-77,-77,0.0,0,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0,NaN,NaN,NaN,NaN,NaN,-77,NaN,NaN,NaN,NaN,NaN,-77,NaN,1,-77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17569,1,5522014,552,ZIM,Zimbabwe,2014,0,0.0,5,1,4,4.0,1,2,2,4,5,3,3,7.0,5,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17570,1,5522015,552,ZIM,Zimbabwe,2015,0,0.0,5,1,4,4.0,2,2,2,4,5,3,3,7.0,5,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17571,1,5522016,552,ZIM,Zimbabwe,2016,0,0.0,5,1,4,4.0,3,2,2,4,5,3,3,7.0,5,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17572,1,5522017,552,ZIM,Zimbabwe,2017,0,0.0,5,1,4,4.0,4,2,2,4,5,3,3,7.0,5,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17573,1,5522018,552,ZIM,Zimbabwe,2018,0,0.0,5,1,4,4.0,5,2,2,4,5,3,3,7.0,5,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_p5d = pd.read_excel('../data/raw/Polity-Project/p5v2018d.xls')
df_p5d.drop(['p5', 'polity'], axis=1, inplace=True)

df_p5d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 22 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   present  185 non-null    object
 1   ccode    1692 non-null   int64
 2   scode    1692 non-null   object
 3   country  1692 non-null   object
 4   persist  1671 non-null   float64
 5   bmonth   1692 non-null   int64
 6   bday     1692 non-null   int64
 7   byear    1692 non-null   int64
 8   emonth   1692 non-null   int64
 9   eday     1692 non-null   int64
 10  eyear    1692 non-null   int64
 11  democ    1692 non-null   int64
 12  autoc    1692 non-null   int64
 13  xrreg    1692 non-null   int64
 14  xrcomp   1692 non-null   int64
 15  xropen   1692 non-null   int64
 16  xconst   1692 non-null   int64
 17  parreg   1692 non-null   int64
 18  parcomp  1692 non-null   int64
 19  exrec    1687 non-null   float64
 20  exconst  1692 non-null   int64
 21  polcomp  1687 non-null   float64
dtypes: float64(3), int64(16), object(3)
memory usage: 290.9+ KB

In [8]:
df_p5d.loc[(df_p5d.scode == 'AFG') & (df_p5d.byear >= 1990)].sort_values(by='byear')

,present,ccode,scode,country,persist,bmonth,bday,byear,emonth,eday,eyear,democ,autoc,xrreg,xrcomp,xropen,xconst,parreg,parcomp,exrec,exconst,polcomp
10,NaN,700,AFG,Afghanistan,4.0,4,17,1992,9,26,1996,-77,-77,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0
11,NaN,700,AFG,Afghanistan,5.0,9,27,1996,10,7,2001,0,7,1,0,0,1,4,1,4.0,1,1.0
12,NaN,700,AFG,Afghanistan,0.0,10,8,2001,12,22,2001,-77,-77,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0
13,NaN,700,AFG,Afghanistan,13.0,12,23,2001,12,28,2014,-66,-66,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0
14,1,700,AFG,Afghanistan,4.0,12,29,2014,99,99,9999,1,2,2,1,4,4,1,0,3.0,4,4.0

In [9]:
df_p5d.loc[(df_p5d.byear >= 1990)].sort_values(by='byear')

,present,ccode,scode,country,persist,bmonth,bday,byear,emonth,eday,eyear,democ,autoc,xrreg,xrcomp,xropen,xconst,parreg,parcomp,exrec,exconst,polcomp
786,NaN,437,IVO,Cote D'Ivoire,4.0,5,31,1990,12,8,1993,0,7,2,1,4,2,4,2,3.0,2,2.0
876,NaN,570,LES,Lesotho,1.0,3,5,1990,5,12,1991,0,7,2,0,0,1,4,1,5.0,1,1.0
870,NaN,660,LEB,Lebanon,14.0,9,22,1990,4,26,2005,-66,-66,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0
861,NaN,450,LBR,Liberia,6.0,9,17,1990,8,17,1996,-77,-77,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0
263,NaN,471,CAO,Cameroon,2.0,12,19,1990,10,11,1992,1,4,2,1,4,2,2,3,3.0,2,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
919,1,820,MAL,Malaysia,1.0,5,10,2018,99,99,9999,7,0,3,3,4,5,2,4,8.0,5,9.0
866,1,450,LBR,Liberia,1.0,1,22,2018,99,99,9999,8,1,3,3,4,6,3,4,8.0,6,8.0
1600,.,2,USA,United States,1.0,3,22,2019,2,4,2020,7,0,3,3,4,6,2,3,8.0,6,7.0
1601,.,2,USA,United States,1.0,2,5,2020,11,2,2020,6,0,3,3,4,5,2,3,8.0,5,7.0
1602,1,2,USA,United States,0.0,11,3,2020,99,99,9999,5,0,3,3,4,4,2,3,8.0,4,7.0

In [10]:
df_p5.loc[(df_p5.scode=='AFG') & (df_p5.year >= 1990)].sort_values(by='year')

,p5,cyear,ccode,scode,country,year,flag,fragment,democ,autoc,polity,polity2,durable,xrreg,xrcomp,xropen,xconst,parreg,parcomp,exrec,exconst,polcomp,prior,emonth,eday,eyear,eprec,interim,bmonth,bday,byear,bprec,post,change,d5,sf,regtrans
190,0,7001990,700,AFG,Afghanistan,1990,0,NaN,0,8,-8,-8.0,1,2,1,4,2,4,1,3.0,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,0,7001991,700,AFG,Afghanistan,1991,0,NaN,0,8,-8,-8.0,2,2,1,4,2,4,1,3.0,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,0,7001992,700,AFG,Afghanistan,1992,0,NaN,-77,-77,-77,0.0,0,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0,-8,4,16,1992,2,-77,NaN,NaN,NaN,NaN,NaN,-77,NaN,1,-77
193,0,7001993,700,AFG,Afghanistan,1993,0,NaN,-77,-77,-77,0.0,0,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0,NaN,NaN,NaN,NaN,NaN,-77,NaN,NaN,NaN,NaN,NaN,-77,NaN,1,-77
194,0,7001994,700,AFG,Afghanistan,1994,0,NaN,-77,-77,-77,0.0,0,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0,NaN,NaN,NaN,NaN,NaN,-77,NaN,NaN,NaN,NaN,NaN,-77,NaN,1,-77
195,0,7001995,700,AFG,Afghanistan,1995,0,NaN,-77,-77,-77,0.0,0,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0,NaN,NaN,NaN,NaN,NaN,-77,NaN,NaN,NaN,NaN,NaN,-77,NaN,1,-77
196,0,7001996,700,AFG,Afghanistan,1996,0,NaN,0,7,-7,-7.0,0,1,0,0,1,4,1,4.0,1,1.0,-8,4,16,1992,2,-77,9,27,1996,9,-7,1,1,1,0
197,0,7001997,700,AFG,Afghanistan,1997,0,NaN,0,7,-7,-7.0,1,1,0,0,1,4,1,4.0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,0,7001998,700,AFG,Afghanistan,1998,0,NaN,0,7,-7,-7.0,2,1,0,0,1,4,1,4.0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,0,7001999,700,AFG,Afghanistan,1999,0,NaN,0,7,-7,-7.0,3,1,0,0,1,4,1,4.0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,0,7002000,700,AFG,Afghanistan,2000,0,2.0,0,7,-7,-7.0,4,1,0,0,1,4,1,4.0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,0,7002001,700,AFG,Afghanistan,2001,0,2.0,-66,-66,-66,NaN,0,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0,-7,10,7,2001,1,-77,12,23,2001,2,-66,-66,NaN,1,-66
202,0,7002002,700,AFG,Afghanistan,2002,0,2.0,-66,-66,-66,NaN,0,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,-66
203,0,7002003,700,AFG,Afghanistan,2003,0,2.0,-66,-66,-66,NaN,0,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,-66
204,0,7002004,700,AFG,Afghanistan,2004,0,2.0,-66,-66,-66,NaN,0,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,-66
205,0,7002005,700,AFG,Afghanistan,2005,0,2.0,-66,-66,-66,NaN,0,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,-66
206,0,7002006,700,AFG,Afghanistan,2006,0,2.0,-66,-66,-66,NaN,0,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,-66
207,0,7002007,700,AFG,Afghanistan,2007,0,2.0,-66,-66,-66,NaN,0,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,-66
208,0,7002008,700,AFG,Afghanistan,2008,0,2.0,-66,-66,-66,NaN,0,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,-66
209,0,7002009,700,AFG,Afghanistan,2009,0,2.0,-66,-66,-66,NaN,0,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,-66
210,0,7002010,700,AFG,Afghanistan,2010,0,2.0,-66,-66,-66,NaN,0,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,-66
211,0,7002011,700,AFG,Afghanistan,2011,0,2.0,-66,-66,-66,NaN,0,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,-66
212,0,7002012,700,AFG,Afghanistan,2012,0,2.0,-66,-66,-66,NaN,0,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,-66
213,0,7002013,700,AFG,Afghanistan,2013,0,2.0,-66,-66,-66,NaN,0,-66,-66,-66,-66,-66,-66,-66.0,-66,-66.0,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,NaN,NaN,NaN,-66,NaN,NaN,-66
214,0,7002014,700,AFG,Afghanistan,2014,0,2.0,1,2,-1,-1.0,0,2,1,4,4,1,0,3.0,4,4.0,-7,10,7,2001,1,-66,12,29,2014,2,-1,6,1,NaN,1
215,0,7002015,700,AFG,Afghanistan,2015,0,2.0,1,2,-1,-1.0,1,2,1,4,4,1,0,3.0,4,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,0,7002016,700,AFG,Afghanistan,2016,0,2.0,1,2,-1,-1.0,2,2,1,4,4,1,0,3.0,4,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,0,7002017,700,AFG,Afghanistan,2017,0,2.0,1,2,-1,-1.0,3,2,1,4,4,1,0,3.0,4,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,0,7002018,700,AFG,Afghanistan,2018,0,2.0,1,2,-1,-1.0,4,2,1,4,4,1,0,3.0,4,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Decision: pursue **P5D** version

In [11]:
df = df_p5d.copy()
df

,present,ccode,scode,country,persist,bmonth,bday,byear,emonth,eday,eyear,democ,autoc,xrreg,xrcomp,xropen,xconst,parreg,parcomp,exrec,exconst,polcomp
0,NaN,700,AFG,Afghanistan,NaN,1,1,1800,6,30,1935,1,7,3,1,1,1,3,3,1.0,1,6.0
1,NaN,700,AFG,Afghanistan,10.0,7,1,1935,6,30,1945,0,8,3,1,1,1,3,2,1.0,1,3.0
2,NaN,700,AFG,Afghanistan,8.0,7,1,1945,9,7,1953,0,10,3,1,1,1,4,1,1.0,1,1.0
3,NaN,700,AFG,Afghanistan,11.0,9,8,1953,9,9,1964,0,10,3,1,2,1,4,1,2.0,1,1.0
4,NaN,700,AFG,Afghanistan,9.0,9,10,1964,7,17,1973,0,7,3,1,2,3,4,2,2.0,3,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1687,NaN,552,ZIM,Zimbabwe,12.0,12,23,1987,9,10,1999,0,6,2,1,4,3,4,2,3.0,3,2.0
1688,NaN,552,ZIM,Zimbabwe,2.0,9,11,1999,7,26,2001,1,4,2,1,4,3,3,3,3.0,3,6.0
1689,NaN,552,ZIM,Zimbabwe,8.0,7,27,2001,2,10,2009,1,5,2,1,4,2,3,3,3.0,2,6.0
1690,NaN,552,ZIM,Zimbabwe,4.0,2,11,2009,5,21,2013,3,2,2,2,4,3,3,3,7.0,3,6.0
1691,1,552,ZIM,Zimbabwe,6.0,5,22,2013,99,99,9999,5,1,2,2,4,5,3,3,7.0,5,6.0

### Country names codes

Make consistent with other data sources to enable merging. Minor differences in spelling, abbreviations, casing, etc. make this necessary. Process completed in simple Excel file for simplicity. Import that lookup table to convert to new naming schemes.

In [12]:
df.loc[(df.scode=='YAR') | (df.scode=='YEM') | (df.scode=="YPR")]

,present,ccode,scode,country,persist,bmonth,bday,byear,emonth,eday,eyear,democ,autoc,xrreg,xrcomp,xropen,xconst,parreg,parcomp,exrec,exconst,polcomp
1633,NaN,678,YAR,Yemen North,28.0,10,30,1918,6,30,1946,0,10,3,1,1,1,4,1,1.0,1,1.0
1634,NaN,678,YAR,Yemen North,2.0,7,1,1946,2,17,1948,-88,-88,-88,-88,-88,-88,-88,-88,-88.0,-88,-88.0
1635,NaN,678,YAR,Yemen North,15.0,2,18,1948,9,19,1962,1,7,3,1,1,1,3,3,1.0,1,6.0
1636,NaN,678,YAR,Yemen North,4.0,9,20,1962,11,5,1966,2,2,1,0,0,5,3,2,4.0,5,3.0
1637,NaN,678,YAR,Yemen North,8.0,11,6,1966,6,13,1974,0,3,1,0,0,3,3,2,4.0,3,3.0
1638,NaN,678,YAR,Yemen North,3.0,6,14,1974,10,11,1977,0,4,2,0,0,3,4,2,5.0,3,2.0
1639,NaN,678,YAR,Yemen North,11.0,10,12,1977,6,30,1988,0,6,2,1,4,3,4,2,3.0,3,2.0
1640,NaN,678,YAR,Yemen North,2.0,7,1,1988,5,21,1990,0,5,2,1,4,3,3,2,3.0,3,3.0
1641,NaN,679,YEM,Yemen,3.0,5,22,1990,4,27,1993,-88,-88,-88,-88,-88,-88,-88,-88,-88.0,-88,-88.0
1642,NaN,679,YEM,Yemen,20.0,4,28,1993,2,21,2012,1,3,2,0,0,2,3,3,5.0,2,6.0
1643,NaN,679,YEM,Yemen,3.0,2,22,2012,9,21,2014,3,0,2,0,0,5,2,3,5.0,5,7.0
1644,1,679,YEM,Yemen,4.0,9,22,2014,99,99,9999,-77,-77,-77,-77,-77,-77,-77,-77,-77.0,-77,-77.0
1651,NaN,680,YPR,Yemen South,3.0,11,30,1967,11,30,1970,0,5,2,1,4,3,3,2,3.0,3,3.0
1652,NaN,680,YPR,Yemen South,4.0,12,1,1970,6,30,1974,0,6,2,1,4,3,4,2,3.0,3,2.0
1653,NaN,680,YPR,Yemen South,4.0,7,1,1974,12,27,1978,0,7,2,1,4,3,4,1,3.0,3,1.0
1654,NaN,680,YPR,Yemen South,7.0,12,28,1978,2,6,1986,0,8,2,1,4,2,4,1,3.0,2,1.0
1655,NaN,680,YPR,Yemen South,4.0,2,7,1986,5,21,1990,0,7,2,1,4,3,4,1,3.0,3,1.0

In [13]:
df_naming_lookup = pd.read_excel('../src/country_codes_regimes.xlsx')
renaming_dict = dict(zip(df_naming_lookup.country_original, df_naming_lookup.country_final))
scode_dict = dict(zip(df_naming_lookup.scode_original, df_naming_lookup.scode_final))

df['country_final'] = df.country.map(renaming_dict)
df['scode_final'] = df.scode.map(scode_dict)

display(df[['ccode', 'scode', 'scode_final', 'country', 'country_final']].drop_duplicates().sort_values(by='country'))
df.drop(['ccode', 'scode', 'country'], axis=1, inplace=True)

# Misc. renaming
df.rename(columns={'country_final': 'country',
                       'scode_final': 'scode'}, inplace=True)

,ccode,scode,scode_final,country,country_final
0,700,AFG,AFG,Afghanistan,Afghanistan
15,339,ALB,ALB,Albania,Albania
28,615,ALG,ALG,Algeria,Algeria
34,540,ANG,ANG,Angola,Angola
40,160,ARG,ARG,Argentina,Argentina
64,371,ARM,ARM,Armenia,Armenia
71,900,AUL,AUS,Australia,Australia
72,305,AUS,AUT,Austria,Austria
87,373,AZE,AZE,Azerbaijan,Azerbaijan
92,267,BAD,BAD,Baden,Baden
95,692,BAH,BAH,Bahrain,Bahrain
150,771,BNG,BNG,Bangladesh,Bangladesh
105,245,BAV,BAV,Bavaria,Bavaria
146,370,BLR,BLR,Belarus,Belarus
109,211,BEL,BEL,Belgium,Belgium
120,434,BEN,BEN,Benin,Benin
141,760,BHU,BHU,Bhutan,Bhutan
164,145,BOL,BOL,Bolivia,Bolivia
188,346,BOS,BOS,Bosnia,Bosnia
190,571,BOT,BOT,Botswana,Botswana
193,140,BRA,BRA,Brazil,Brazil
222,355,BUL,BUL,Bulgaria,Bulgaria
129,439,BFO,BFO,Burkina Faso,Burkina Faso
210,516,BUI,BUI,Burundi,Burundi
241,811,CAM,CAM,Cambodia,Cambodia
257,471,CAO,CAO,Cameroon,Cameroon
254,20,CAN,CAN,Canada,Canada
265,402,CAP,CAP,Cape Verde,Cape Verde
270,482,CEN,CEN,Central African Republic,Central African Republic
277,483,CHA,CHA,Chad,Chad
289,155,CHL,CHL,Chile,Chile
306,710,CHN,CHN,China,China
320,100,COL,COL,Colombia,Colombia
333,581,COM,COM,Comoros,Comoros
1669,490,ZAI,ZAI,Congo Kinshasa,Congo Kinshasa
349,484,CON,CON,Congo-Brazzaville,Congo-Brazzaville
358,94,COS,COS,Costa Rica,Costa Rica
785,437,IVO,IVO,Cote D'Ivoire,Cote D'Ivoire
368,344,CRO,CRO,Croatia,Croatia
373,40,CUB,CUB,Cuba,Cuba
386,352,CYP,CYP,Cyprus,Cyprus
402,316,CZR,CZR,Czech Republic,Czech Republic
391,315,CZE,CZR,Czechoslovakia,Czech Republic
404,390,DEN,DEN,Denmark,Denmark
413,522,DJI,DJI,Djibouti,Djibouti
418,42,DOM,DOM,Dominican Republic,Dominican Republic
435,130,ECU,ECU,Ecuador,Ecuador
449,651,EGY,EGY,Egypt,Egypt
1279,92,SAL,SLV,El Salvador,El Salvador
456,411,EQG,EQG,Equatorial Guinea,Equatorial Guinea
460,531,ERI,ERI,Eritrea,Eritrea
462,366,EST,EST,Estonia,Estonia
479,529,ETI,ETI,Ethiopia,Ethiopia
470,530,ETH,ETI,Ethiopia,Ethiopia
491,950,FJI,FJI,Fiji,Fiji
486,375,FIN,FIN,Finland,Finland
504,220,FRN,FRN,France,France
526,481,GAB,GAB,Gabon,Gabon
531,420,GAM,GAM,Gambia,Gambia
618,372,GRG,GRG,Georgia,Georgia
573,255,GMY,GMY,Germany,Germany
541,265,GDR,GDR,Germany East,Germany East
546,260,GFR,GMY,Germany West,Germany
548,452,GHA,GHA,Ghana,Ghana
538,99,GCL,GCL,Gran Colombia,Gran Colombia
594,350,GRC,GRC,Greece,Greece
626,90,GUA,GUA,Guatemala,Guatemala
654,438,GUI,GUI,Guinea,Guinea
581,404,GNB,GNB,Guinea-Bissau,Guinea-Bissau
661,110,GUY,GUY,Guyana,Guyana
667,41,HAI,HAI,Haiti,Haiti
690,91,HON,HON,Honduras,Honduras
714,310,HUN,HUN,Hungary,Hungary
727,750,IND,IND,India,India
733,850,INS,INS,Indonesia,Indonesia
749,630,IRN,IRN,Iran,Iran
764,645,IRQ,IRQ,Iraq,Iraq
745,205,IRE,IRE,Ireland,Ireland
775,666,ISR,ISR,Israel,Israel
778,325,ITA,ITA,Italy,Italy
794,51,JAM,JAM,Jamaica,Jamaica
805,740,JPN,JPN,Japan,Japan
796,663,JOR,JOR,Jordan,Jordan
841,705,KZK,KZK,Kazakhstan,Kazakhstan
810,501,KEN,KEN,Kenya,Kenya
822,730,KOR,KOR,Korea,Korea
1217,731,PRK,PRK,Korea North,Korea North
1222,732,ROK,KOR,Korea South,Korea South
823,341,KOS,KOS,Kosovo,Kosovo
824,690,KUW,KUW,Kuwait,Kuwait
833,703,KYR,KYR,Kyrgyzstan,Kyrgyzstan
843,812,LAO,LAO,Laos,Laos
849,367,LAT,LAT,Latvia,Latvia
867,660,LEB,LEB,Lebanon,Lebanon
872,570,LES,LES,Lesotho,Lesotho
854,450,LBR,LBR,Liberia,Liberia
883,620,LIB,LIB,Libya,Libya
888,368,LIT,LIT,Lithuania,Lithuania
901,343,MAC,MAC,Macedonia,Macedonia
903,580,MAG,MAG,Madagascar,Madagascar
922,553,MAW,MAW,Malawi,Malawi
912,820,MAL,MAL,Malaysia,Malaysia
954,432,MLI,MLI,Mali,Mali
893,435,MAA,MAA,Mauritania,Mauritania
920,590,MAS,MAS,Mauritius,Mauritius
929,70,MEX,MEX,Mexico,Mexico
964,332,MOD,MOD,Modena,Modena
950,359,MLD,MLD,Moldova,Moldova
965,712,MON,MON,Mongolia,Mongolia
963,348,MNT,MNT,Montenegro,Montenegro
971,600,MOR,MOR,Morocco,Morocco
993,541,MZM,MZM,Mozambique,Mozambique
980,775,MYA,MYA,Myanmar (Burma),Myanmar (Burma)
998,565,NAM,NAM,Namibia,Namibia
999,790,NEP,NEP,Nepal,Nepal
1065,210,NTH,NTH,Netherlands,Netherlands
1015,920,NEW,NEW,New Zealand,New Zealand
1019,93,NIC,NIC,Nicaragua,Nicaragua
1044,436,NIR,NIR,Niger,Niger
1032,475,NIG,NIG,Nigeria,Nigeria
1059,385,NOR,NOR,Norway,Norway
1074,698,OMA,OMA,Oman,Oman
1073,564,OFS,OFS,Orange Free State,Orange Free State
1079,770,PAK,PAK,Pakistan,Pakistan
1166,769,PKS,PAK,Pakistan,Pakistan
1092,95,PAN,PAN,Panama,Panama
1103,327,PAP,PAP,Papal States,Papal States
1176,910,PNG,PNG,Papua New Guinea,Papua New Guinea
1106,150,PAR,PAR,Paraguay,Paraguay
1175,335,PMA,PMA,Parma,Parma
1124,135,PER,PER,Peru,Peru
1154,840,PHI,PHI,Philippines,Philippines
1178,290,POL,POL,Poland,Poland
1192,235,POR,POR,Portugal,Portugal
563,255,GMY,GMY,Prussia,Germany
1221,694,QAT,QAT,Qatar,Qatar
1234,360,RUM,RUM,Romania,Romania
1251,365,RUS,RUS,Russia,Russia
1266,517,RWA,RWA,Rwanda,Rwanda
1294,324,SAR,SAR,Sardinia,Sardinia
1296,670,SAU,SAU,Saudi Arabia,Saudi Arabia
1297,269,SAX,SAX,Saxony,Saxony
1306,433,SEN,SEN,Senegal,Senegal
1314,342,SER,SER,Serbia,Serbia
1650,347,YGS,YGS,Serbia and Montenegro,Yugoslavia
1328,451,SIE,SIE,Sierra Leone,Sierra Leone
1341,830,SIN,SIN,Singapore,Singapore
1342,317,SLO,SLO,Slovak Republic,Slovak Republic
1345,349,SLV,SNV,Slovenia,Slovenia
1346,940,SOL,SOL,Solomon Islands,Solomon Islands
1352,520,SOM,SOM,Somalia,Somalia
1275,560,SAF,SAF,South Africa,South Africa
1400,525,SSU,SSU,South Sudan,South Sudan
1262,817,RVN,RVN,South Vietnam,South Vietnam
1358,230,SPN,SPN,Spain,Spain
1386,780,SRI,SRI,Sri Lanka,Sri Lanka
1402,625,SUD,SUD,Sudan,Sudan
1305,626,SDN,SUD,Sudan-North,Sudan
1417,115,SUR,SUR,Suriname,Suriname
1424,572,SWA,SWZ,Swaziland,Swaziland
1431,380,SWD,SWE,Sweden,Sweden
1439,225,SWZ,CHE,Switzerland,Switzerland
1440,652,SYR,SYR,Syria,Syria
1458,713,TAW,TAW,Taiwan,Taiwan
1453,702,TAJ,TAJ,Tajikistan,Tajikistan
1465,510,TAZ,TAZ,Tanzania,Tanzania
1469,800,THI,THI,Thailand,Thailand
483,860,ETM,ETM,Timor Leste,Timor Leste
1497,461,TOG,TOG,Togo,Togo
1503,52,TRI,TRI,Trinidad and Tobago,Trinidad and Tobago
1507,616,TUN,TUN,Tunisia,Tunisia
1516,640,TUR,TUR,Turkey,Turkey
1494,701,TKM,TKM,Turkmenistan,Turkmenistan
1540,337,TUS,TUS,Tuscany,Tuscany
1325,329,SIC,SIC,Two Sicilies,Two Sicilies
1603,364,USR,USR,USSR,USSR
1544,500,UGA,UGA,Uganda,Uganda
1562,369,UKR,UKR,Ukraine,Ukraine
1543,696,UAE,UAE,United Arab Emirates,United Arab Emirates
1556,200,UKG,UKG,United Kingdom,United Kingdom
1571,89,UPC,UPC,United Provinces,United Provinces
1583,2,USA,USA,United States,United States
1572,165,URU,URU,Uruguay,Uruguay
1610,704,UZB,UZB,Uzbekistan,Uzbekistan
1611,101,VEN,VEN,Venezuela,Venezuela
1630,818,VIE,VIE,Vietnam,Vietnam
432,816,DRV,DRV,Vietnam North,Vietnam North
1631,271,WRT,WRT,Wuerttemburg,Wuerttemburg
1641,679,YEM,YEM,Yemen,Yemen
1633,678,YAR,YEM,Yemen North,Yemen
1651,680,YPR,YPR,Yemen South,Yemen South
1645,347,YGS,YGS,Yugoslavia,Yugoslavia
1656,345,YUG,YGS,Yugoslavia,Yugoslavia
1677,551,ZAM,ZAM,Zambia,Zambia
1685,552,ZIM,ZIM,Zimbabwe,Zimbabwe

### Remove <3pt changes
- IF THE 1-POINT CHANGE PROVES UNHELPFUL IN FINAL MODEL, TRY IMPLEMENTING A 3-POINT CHANGE INSTEAD
- Determine extent of change in terms of points in each index
- Adjust from "1 point" change in "persist" to "3 point" change in "durable"

In [14]:
MIN_CHG = 3
df.drop(['democ', 'autoc', 'xrreg'], axis=1, inplace=True)
component_vars = ['xrcomp', 'xropen', 'xconst', 'parcomp', 'parreg']


def calc_chg(old_list, new_list):
    if type(old_list) == type(0):
        old_list = np.zeros(3).astype('int')
    chg = 0
    for old, new in zip(old_list, new_list):
        chg += abs(old-new)
    return int(chg)


# Loop over all country names
pt_chg = []
delete_count = 0
for country in df.country.unique():
    # list of dataframe indices for the selected country
    df_country = df.loc[df.country==country].copy()
    
    for index in df_country.index:
        
        # first iteration
        if index == df_country.index[0]:
            last_vars = 0
        
        
        current_vars = df_country.loc[index, component_vars]
        chg = calc_chg(last_vars, current_vars)
        
        # last row for this country
        if df_country.loc[index, 'present'] == 1:
            pt_chg.append(chg)
        
        # if chg <3, delete row
        elif chg < MIN_CHG:
            df.drop(index, inplace=True)
            df_country.drop(index, inplace=True)
            delete_count += 1
        
        
        else:
            pt_chg.append(chg)
            
            # update for next iteration
            last_vars = current_vars

print('Disqualified transitions:', delete_count)

Disqualified transitions: 402

#### Convert day/month/year to datetime

In [15]:
# "START" datetime
cols = ['bmonth', 'bday', 'byear']
dt_start = df[cols].copy()
dt_start.columns = ['month', 'day', 'year']

# Add to main dataframe
df['startdate'] = pd.to_datetime(dt_start)

# Drop old columns
df.drop(cols, axis=1, inplace=True)

In [16]:
# "END" datetime
# Note added complexity compared to "start" because current regimes are 
# indicated by emonth=99, eday=99, eyear=99. Convert these to a far future date instead
# such that datetime conversions work
cols = ['emonth', 'eday', 'eyear']
dt_end = df[cols].copy()
dt_end.columns = ['month', 'day', 'year']

# Replace placeholders with far-distant dates
MAX_YEAR = df.startdate.dt.year.max()
MAX_MONTH = df.startdate.dt.month.max()
MAX_DAY = df.startdate.dt.day.max()
dt_end.year.replace(9999, MAX_YEAR, inplace=True)
dt_end.month.replace(99, MAX_MONTH, inplace=True)
dt_end.day.replace(99, MAX_DAY, inplace=True)


# Add to main dataframe
df['enddate'] = pd.to_datetime(dt_end)

# Drop old columns
df.drop(cols, axis=1, inplace=True)

# Drop duplicate column (duplicates xconst, as indicated by data manual)
df.drop('exconst', axis=1, inplace=True)

# Drop unused "concept variable"
df.drop('polcomp', axis=1, inplace=True)

# Sort
df.sort_values(by=['country', 'startdate'], inplace=True)
df.reset_index(inplace=True, drop=True)

In [17]:
# FIX INCORRECT "ENDDATE" VALUES

# New column to ensure that the enddate is determined consistently
df['enddate_QC'] = None

# Loop over all country names
for country in df.country.unique():

    # list of dataframe indices for the selected country
    indices = df.loc[df.country==country].index
    
    # Loop over all indices *except the last index*
    for index in indices[:-1]:
        
        # Add 1 to the startdate of the subsequent row
        df.loc[index, 'enddate_QC'] = df.loc[index+1, 'startdate']-datetime.timedelta(days=1)
        
    # Handle the last index differently (i.e. it is always correct by definition)
    df.loc[indices[-1], 'enddate_QC'] = df.loc[indices[-1], 'enddate']
    
print("Cases where original enddate != QC'd value:")
display(df.loc[df.enddate != df.enddate_QC])

# After careful QC of the selected values, it is determined that the QC values are more valuable than the original
# Overwrite old and use QC instead. Delete QC
df.drop('enddate', axis=1, inplace=True)
df.rename(columns={'enddate_QC': 'enddate'}, inplace=True)

# Convert from 'object' to 'datetime' format
df['enddate'] = pd.to_datetime(df['enddate'])


# Incorporate new column for "duration"
df['duration_yrs'] = (df.enddate - df.startdate).dt.days / 365.2425 # average number of days per year

Cases where original enddate != QC'd value:

,present,persist,xrcomp,xropen,xconst,parreg,parcomp,exrec,country,scode,startdate,enddate,enddate_QC
0,NaN,NaN,1,1,1,3,3,1.0,Afghanistan,AFG,1800-01-01,1935-06-30,1945-06-30 00:00:00
1,NaN,8.0,1,1,1,4,1,1.0,Afghanistan,AFG,1945-07-01,1953-09-07,1964-09-09 00:00:00
3,NaN,3.0,0,0,1,4,1,4.0,Afghanistan,AFG,1973-07-18,1976-12-31,1978-04-16 00:00:00
20,NaN,4.0,3,4,5,3,3,8.0,Albania,ALB,1992-04-06,1996-05-26,2002-07-24 00:00:00
23,NaN,3.0,1,4,2,4,1,3.0,Algeria,ALG,1962-07-05,1965-06-19,1989-02-23 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282,NaN,4.0,3,4,3,3,3,8.0,Zambia,ZAM,1964-10-24,1968-08-14,1972-12-08 00:00:00
1284,NaN,5.0,3,4,5,2,3,8.0,Zambia,ZAM,1991-11-01,1996-11-18,2016-06-09 00:00:00
1286,NaN,3.0,2,4,5,3,3,7.0,Zimbabwe,ZIM,1980-04-18,1983-03-08,1987-12-22 00:00:00
1287,NaN,12.0,1,4,3,4,2,3.0,Zimbabwe,ZIM,1987-12-23,1999-09-10,2001-07-26 00:00:00
1288,NaN,8.0,1,4,2,3,3,3.0,Zimbabwe,ZIM,2001-07-27,2009-02-10,2013-05-21 00:00:00

In [18]:
# Difference between "duration" and "persist" values

# df[['duration_yrs', 'persist']]

# compare = pd.DataFrame([df.duration_yrs, df.persist]).T
# compare['equal?'] = compare.duration_yrs == compare.persist
# compare['difference'] = df.duration_yrs - df.persist

# compare.dropna(inplace=True)

# temp = df.loc[compare.loc[(compare.difference >= 1) | (compare.difference <= -1)].index]
# temp = temp.loc[temp.present != 1].copy()
# temp['change'] = temp.duration_yrs - temp.persist
# temp.sort_values(by='change')

In [19]:
# Government classifiers

# - democ: democracy index (0-10)
# - autoc: autocracy index (0-10)
# - xrreg: regulation of chief executive recruitment
# - xrcomp: competitiveness of executive recruitment
# - xropen: openness of executive recruitment
# - xconst: executive constraints ("decision rules")
# - parreg: regulation of participation
# - parcomp: competitiveness of participations
# - exrec: executive recruitment (combines xrreg, xrcomp, xropen)
# - exconst: executive constraints (identical to xconst)
# - polcomp: political competition (combines parreg and parcomp)



# DEMOC = XRCOMP + XROPEN + XCONST + PARCOMP
# AUTOC = XRCOMP + XROPEN + XCONST + PARCOMP + PARREG
# point_change = delta(xrcomp) + delta(xropen) + delta(xconst) + delta(parcomp) + delta(parreg)

## Export results!

In [20]:
# Only use columns that are used in final model
df_final = df[['country', 'scode', 'startdate', 'enddate', 'duration_yrs']]

# Export to SQL
from sqlalchemy import create_engine
engine = create_engine('sqlite:///../data/processed/regime_changes.db')
with engine.begin() as connection:
    df_final.to_sql(name='regime_changes', con=connection, if_exists='replace', index=False)

In [21]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1290 entries, 0 to 1289
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       1290 non-null   object
 1   scode         1290 non-null   object
 2   startdate     1290 non-null   datetime64[ns]
 3   enddate       1290 non-null   datetime64[ns]
 4   duration_yrs  1290 non-null   float64
dtypes: datetime64[ns](2), float64(1), object(2)
memory usage: 50.5+ KB

In [22]:
df_final

          country scode  startdate    enddate  duration_yrs
0     Afghanistan   AFG 1800-01-01 1945-06-30    145.492378
1     Afghanistan   AFG 1945-07-01 1964-09-09     19.192728
2     Afghanistan   AFG 1964-09-10 1973-07-17      8.848915
3     Afghanistan   AFG 1973-07-18 1978-04-16      4.744793
4     Afghanistan   AFG 1978-04-17 1979-12-27      1.694764
...           ...   ...        ...        ...           ...
1285       Zambia   ZAM 2016-06-10 2020-12-31      4.558615
1286     Zimbabwe   ZIM 1980-04-18 1987-12-22      7.677091
1287     Zimbabwe   ZIM 1987-12-23 2001-07-26     13.590970
1288     Zimbabwe   ZIM 2001-07-27 2013-05-21     11.816807
1289     Zimbabwe   ZIM 2013-05-22 2020-12-31      7.611381

[1290 rows x 5 columns]